db
blackenkeeper/go-db-sql-final pull request #1
Opened 2024-02-18 20:11 UTC by blackenkeeper

2024-02-18 21:19 UTC, robotomize requested changes
Отличная работа, добавьте проверку rows.Err() и проверку статуса в адресе и можем идти дальше

2024-02-18 21:19 UTC, robotomize commented on parcel.go
> +		log.Println(err)
Логировать лучше на уровне выше, где-то в main

2024-02-18 21:19 UTC, robotomize commented on parcel.go
> +	}
Нужно обработать еще rows.Err() после вашего цикла получения набора строк

2024-02-18 21:19 UTC, robotomize commented on parcel.go
> +	updateQuery := "update parcel set address = :address where number = :number"
менять адрес можно только если значение статуса registered не забудьте что статусы уже описаны в специальных константах в main

2024-02-18 21:19 UTC, robotomize commented on parcel.go
> +	_, err := s.db.Exec(deleteQuery, sql.Named("number", number), sql.Named("status", ParcelStatusRegistered))
А тут верно, видимо в предыдущем методе забыли просто

2024-02-18 21:19 UTC, robotomize commented on parcel_test.go
> +	require.Equal(t, sql.ErrNoRows, err)
Отлично, что проверяете конкретную ошибку

2024-02-18 21:19 UTC, robotomize commented on parcel_test.go
> +		require.NoError(t, err)
Можно без if сразу проверяеть require.NoError ну или если это создание подлючения, то можно и t.Fatal(err) . Это необязательно исправлять, просто заметка

2024-02-19 19:02 UTC, blackenkeeper commented
Никита, приветствую! Спасибо за подробные комментарии, вроде всё исправил

2024-02-19 19:37 UTC, robotomize approved these changes
Принимается! Отлично поработали!

2024-04-09 20:34 UTC, merged