add Dockerfile
blackenkeeper/go-db-sql-final pull request #2
Opened 2024-04-09 20:46 UTC by blackenkeeper

2024-04-09 22:35 UTC, dirtymew requested changes
Привет Владлен

теперь все верно - в целом все верно, но нужно немного подправить

2024-04-09 22:35 UTC, dirtymew commented on Dockerfile
> +COPY go.mod go.sum ./
тут тогда COPY . . а на 5 строке уже не надо копировать ничего

2024-04-09 22:35 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /delivery_app
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 это лучше в ENV указывать

2024-04-09 22:35 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.21.0
отлично что зафиксировал версию

2024-04-10 20:59 UTC, blackenkeeper commented
Привет, Антон! Большое спасибо за подробную обратную связь, получал удовольствие, когда исправлял и понимал, что так действительно круче. Вроде всё сделал, посмотри, пожалуйста

2024-04-10 21:27 UTC, dirtymew approved these changes
Владлен

зачет - вопросов больше нет

2024-04-10 21:27 UTC, dirtymew commented on Dockerfile
> +RUN go mod download
в Dockerfile для улучшения читаемости принято пустыми строками инструкции отделять

2024-04-11 20:26 UTC, blackenkeeper commented on Dockerfile
> +RUN go mod download
Тоже исправил сразу, спасибо)

2024-04-11 20:26 UTC, merged